### ISSUE TITLE
Rain 0.1.2 suggestions

### ISSUE THREAD

**Issue by Taliayaya** [Taliayaya/Project-86#22]
### entire HUD idea

- [x] change opacity of the thing around crosshair when zoom in, it look very weird with the way it is rn (sorry)
- [x] if possible, can it be thinner?

- [x] Range finder
- [x] Sometime after respawn some legion will follow our trail to last known location, this is fine, but some legion get stuck and just won't attack us on new life at all

- [x] Can LMG sound be a bit quieter, currently the sound is louder than explosion
- [x] Can we change scroll mouse sensitivity? I don't know the term but currently it just go like 1 push(or click) a zoom, this make it harder to misscroll but also harder to suddenly zoom in or out

- [x]  add run if possible, maybe like twice the setting speed
- [x] What if we make Lowe's explosion range larger? currently yes it is cool but we can dodge it too easily
- [x]  Maybe tune up turning speed for Lowe a bit, in between the old one I complain and this one we currently use

**Comment by Nairskytear** [comment]
- [ ] Reload key, either individual key for main and sub gun or one key for both
