### ISSUE TITLE
BUGS 1.2-alpha by Excal

### ISSUE THREAD

**Issue by ExcalibursBlad** [Taliayaya/Project-86#24]
- [x] 1. Settings Reset does not work on "sfxVolume" in Sound Settings
- [x] 2. Pause Menu does not open after Reloading Scene
- [ ] 3. Secondary Fire randomly fails
-  First Instance: When Maxing Movement Speed
- Second Instance: After Reloading Scene for about the 10th time
- [ ] 4. Game freezes after Reloading Scene then inputting too many inputs at once

Edit: added check marks

**Comment by Taliayaya** [comment]
- Game freezes after Reloading Scene then inputting too many inputs at once
 Need more explanation, not reproducible / fixed
