### ISSUE TITLE
BUGS 2.0-alpha by Rain

### ISSUE THREAD

**Issue by Nairskytear** [Taliayaya/Project-86#27]
- [x] Aggro for jugg didnt work, it did work for scavenger
- [x] launcher didnt make shortcut
- [x] bullet still slightly to the right
- [x] Big building is uncolliable for legion, legion bullet, and it pathfinding
- [x] sound of engine is unloop, it is quieter when walk instead of other way too
- [ ] respawn doesn't work
- [x] after we use go to command, Fido command will stuck to "go to" until we order anything else even after he reach his destination
- [x] Sound. engine sound is louder when idle instead of walk

Bug that still carry over 
- [x] If pause too early when it restart or respawn, game freeze. If put too many input at once, it crash (discover in 1.2 by Excal)
- [x] Settings Reset does not work on "sfxVolume" in Sound Settings (discover in 1.2 by Excal)
- [ ] Secondary Fire randomly fails still happen. both randomly and after put speed to 100 sometime (discover by rain in 0.1.0, discover more trigger by Excal)
- [x] Pause Menu does not open after Reloading Scene (discover in 1.2 by Excal)
- [x] glitch where we go under floor is still possible, just harder to do (discover in 1.2 by Excal)

**Comment by Taliayaya** [comment]
Wontfix:

- bullet on right
- launcher didn't make a shortcut

**Comment by Taliayaya** [comment]
For the Secondary ammo, is it because of the highspeed? 
![image](https://github.com/Taliayaya/Project-86/assets/84530101/b4eb039e-6c23-41f6-8de3-a8168ac59f21)

It may be because the juggernaut moves so fast that the bullets are quickly not visible anymore
