### ISSUE TITLE
2.0 Suggestion by Rain

### ISSUE THREAD

**Issue by Nairskytear** [Taliayaya/Project-86#28]
Suggestion

- [x] Stair is so weird block, if we could walk up or jump in future this will be good 
- [x] Range finder to help use with 
- [ ] find spot to put control key guide or lord help me
- [x] We could put Fido's Status when destroyed as "destroyed" instead of hide to avoid confusion
- [x] when we fall over the map please just kill us
- [ ] When we get on ledge, what if we can just climb it, or is it idea for jump in the future?
- ~~[ ] We could have up/down degree like +50 -50 and it would work still (when on ground, -50 might not possible because barrel colide but it will be good for when we are up high)~~
- [x] Fix range system stretch out value for range to be bigger, so it would be more reasonable to shoot. for now 10 meter is so absurdly small

**Comment by Taliayaya** [comment]
![image](https://github.com/Taliayaya/Project-86/assets/84530101/e67c1b43-7aee-4188-a7cf-16ca7ea82d92)
Reason why I can't allow the -50 50 angles. I need a bone to be able to just move the cockpit but this is a model issue and I want to keep it as it for now.
