### ISSUE TITLE
User interface issues

### ISSUE THREAD

**Issue by cupid0729** [Taliayaya/Project-86#47]
As shown in the image below, I don't understand why my crosshair has disappeared. Even when I press "Alt," I can't find the crosshair settings.
Is there any solution available?

<img width="960" alt="螢幕擷取畫面 2023-10-01 022339" src="https://github.com/Taliayaya/Project-86/assets/121004861/3533aedf-8748-4867-8833-31f3d7ae2eec">

**Comment by Taliayaya** [comment]
Hello,
Something probably went wrong with the settings. 
It ain't a proper solution but you can try deleting the file in AppData\LocalLow\Project-86-Community\Project-86\ScriptableObjects\AimAreaPanel.data
It contains the save of the position.

**Comment by cupid0729** [comment]
Thank you for your response, the issue has been resolved.
Wishing you smooth development in the future!

**Comment by Taliayaya** [comment]
Thank you as well, wishing you a great time on this game!
